# Auto-label PRs based on files changed
python:
  - changed-files:
      - any-glob-to-any-file:
          - '*.py'
          - '**/*.py'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**/*'
          - '**/*test*.py'
          - 'test_*.py'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'
          - 'docs/**/*'
          - 'README.md'
          - 'LICENSE.md'

ci-cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/**/*'
          - '.github/dependabot.yml'
          - 'build.ps1'
          - '*.spec'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.cfg'
          - '*.toml'
          - '*.ini'
          - '*.json'
          - 'requirements*.txt'

ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'sc_kill_feed_gui.py'
          - 'lib/ui_helpers.py'
          - 'lib/overlay_helpers.py'

lib:
  - changed-files:
      - any-glob-to-any-file:
          - 'lib/**/*.py'

assets:
  - changed-files:
      - any-glob-to-any-file:
          - 'assets/**/*'

